### ISSUE TITLE
Provide an executor to run Cypress tests out of an (Angular) NX-project.

### ISSUE THREAD

**Issue by TheLeanMachine** [kubeshop/testkube#2141]
**Management Summary**
As of now, testkube does run Cypress tests.
But if you aggregate your projects using the [NX-build tool](https://nx.dev/), this won't work out of the box. This FR seeks to change this... ^^

<img width="1647" alt="Screenshot 2022-08-24 at 11 10 01" src="https://user-images.githubusercontent.com/3470837/186379656-017bf228-2e13-45c8-b48a-8d03af8ba9cc.png">

In our company, we use NX _to build & test Angular apps_, so this is my personal, concrete use-case....

(This ticket is a follow-up of a meeting on 28.8.2022 w/ @TheBrunoLopes, @olensmar and a3rd person whose name I forgot. Sorry!)

**Is your feature request related to a problem? Please describe.**
Cannot make use of testkube to run our _aggregated_ Cypress tests.

**Describe the solution you'd like**
I have an option for running [NX-packaged Cypress tests](https://nx.dev/packages/cypress). To be precise, running NX-packaged Cypress tests _for an Angular application_ (if that makes a difference).
This should be configurable analogues to the `cypress/project` type... maybe `cypress/nx-project` or `cypress/nx-agular-project`?
<img width="842" alt="Screenshot 2022-08-24 at 11 13 14" src="https://user-images.githubusercontent.com/3470837/186387210-b46132c6-d78d-40a0-b442-f6541baec1d2.png">

**Describe alternatives you've considered**
My alternative would be to somehow "derive"/"cut out" a pure Cypress project from the aggregated NX-project.
Not really looking forward to do so, tho... ^^

FYI: I just tried to run the nx-cypress-example with this configuration...
<img width="1202" alt="Screenshot 2022-08-24 at 11 01 31" src="https://user-images.githubusercontent.com/3470837/186389761-dc876f3d-81ea-4e73-b95d-af6a62c5e8ba.png">

...and this was the result (didn't expect it to work), tho':
<img width="1730" alt="Screenshot 2022-08-24 at 11 58 34" src="https://user-images.githubusercontent.com/3470837/186390010-7f99ff4a-8501-4d3f-b54e-cb2ec719ddce.png">

For sakes of completeness, this is the stacktrace...
```
It looks like this is your first time using Cypress: 10.6.0

[STARTED] Task without title.
[TITLE]  Verified Cypress!       /home/node/.cache/Cypress/10.6.0/Cypress
[SUCCESS]  Verified Cypress!       /home/node/.cache/Cypress/10.6.0/Cypress

Opening Cypress...
[308:0824/090226.403679:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 488: Permission denied (13)
[488:0824/090226.432957:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
Your configFile is invalid: /tmp/git-sparse-checkout225390548/repo/apps/cart-e2e/cypress.config.ts

It threw an error when required, check the stack trace below:

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /tmp/git-sparse-checkout225390548/repo/apps/cart-e2e/cypress.config.ts
    at new NodeError (node:internal/errors:372:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:80:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:122:38)
    at defaultLoad (node:internal/modules/esm/load:21:20)
    at ESMLoader.load (node:internal/modules/esm/loader:431:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:350:22)
    at new ModuleJob (node:internal/modules/esm/module_job:66:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:369:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:328:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async loadFile (/home/node/.cache/Cypress/10.6.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_require_async_child.js:106:14)
    at async EventEmitter.<anonymous> (/home/node/.cache/Cypress/10.6.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_require_async_child.js:116:32)
```

**Additional context**
I am happy to retest this with our corp's NX-Cypress tests, as soon as the feature is available.

**Comment by tkonieczny** [comment]
After a while of research and checking it locally:
I created very simplified nx project, and added very simple test. I also got exactly the same error, but it was caused by missing `typescript` package. It's possible it's also not available in current cypress image. After installing it I was able to run the simple test:
![Screenshot_20220831_154150](https://user-images.githubusercontent.com/1473096/187692801-006fbd78-297d-48b0-8ddc-bb54bd96f6e5.png)
But, I don't think it's worth trying to "extract" cypress tests in other, more complex cases - there are just too many possible issues.

But, this may be another way of solving this problem - it should make it possible to use nx directly even without the separate executor - only the custom image would be needed: https://github.com/kubeshop/testkube/issues/2133
