### ISSUE TITLE
TypeError: path argument is required to res.sendFile at N.sendFile while running cypress test in Testkube from the git repository.

### ISSUE THREAD

**Issue by hemagupta77** [kubeshop/testkube#3647]
**Describe the bug**
 Getting TypeError: path argument is required to res.sendFile
    at N.sendFile when I try to run my cypress test in Testkube from the git repository.

TypeError: path argument is required to res.sendFile
    at N.sendFile (<embedded>:2792:6230)
    at tryCatcher (/root/.cache/Cypress/12.8.1/Cypress/resources/app/node_modules/bluebird/js/release/util.js:16:23)
    at ret (eval at makeNodePromisifiedEval (/root/.cache/Cypress/12.8.1/Cypress/resources/app/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:14:23)
    at <embedded>:4669:15819
    at tryCatcher (/root/.cache/Cypress/12.8.1/Cypress/resources/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/.cache/Cypress/12.8.1/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/root/.cache/Cypress/12.8.1/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/root/.cache/Cypress/12.8.1/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:606:10)
    at _drainQueueStep (/root/.cache/Cypress/12.8.1/Cypress/resources/app/node_modules/bluebird/js/release/async.js:142:12)
    at _drainQueue (/root/.cache/Cypress/12.8.1/Cypress/resources/app/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/root/.cache/Cypress/12.8.1/Cypress/resources/app/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate._onImmediate (/root/.cache/Cypress/12.8.1/Cypress/resources/app/node_modules/bluebird/js/release/async.js:17:14)
    at process.processImmediate (node:internal/timers:466:21)

**Expected behavior**
I should be able to run the cypress test successfully in Testkube env from the git repository.

**Version / Cluster**
- Which testkube version? 
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
- What Kubernetes version?

**Screenshots**
If applicable, add CLI commands/output to help explain your problem.
 
**Additional context**

**Comment by vsukhin** [comment]
thank you @hemagupta77 we will checkit out

**Comment by vsukhin** [comment]
hey @hemagupta77 can you provide us with a sample of this test, because it looks like quite cypress specific and hard to reproduce?

**Comment by olensmar** [comment]
deprecated functionality..
