### ISSUE TITLE
testkube 1.12.5  build failure due to `completion` command failure

### ISSUE THREAD

**Issue by chenrui333** [kubeshop/testkube#4015]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
  setting up client type (error: failed to get non-interactive client config: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable)
  
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/json-2.6.3/lib/json/add/exception.rb:29:in `encode': "\xE2" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
  	from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/json-2.6.3/lib/json/add/exception.rb:29:in `to_json'
  	from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/json-2.6.3/lib/json/add/exception.rb:29:in `to_json'
  	from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:231:in `rescue in <main>'
  	from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:217:in `<main>'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:12:in `popen_read': Failure while executing; `\{\"SHELL\"=\>\"bash\"\} /home/linuxbrew/.linuxbrew/Cellar/testkube/1.12.5/bin/kubectl-testkube completion bash` exited with 1. Here's the output: (ErrorDuringExecution)
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/5222556647/jobs/9428326275
relates to Homebrew/homebrew-core#133244

**Comment by vsukhin** [comment]
thank you, @chenrui333 will fix it on Monday
